name: Trigger Stock Recording on a CRON Schedule

on:
  schedule:
    - cron: '0 * * * *'
    - cron: '*/10 19-23 * * THU'
    - cron: '*/10 0-2 * * FRI'
jobs:
  build:
    name: Trigger Stock Recording
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X GET https://gntmhub.com/api/market/record-stocks